CREATE DATABASE KIOSKO;

USE [KIOSKO];

CREATE TABLE PERSONA (
PERSONA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
USUARIO_ID INT,
PERSONA_NOMBRE VARCHAR(50) NOT NULL, --NOMBRE DE LA PERSONA
PERSONA_APELLIDO VARCHAR (50) NOT NULL, --APELLIDO DE LA PERSONA
PERSONA_TIPO VARCHAR(50) NOT NULL, -- EMPLEADO O DUEÑO PARA DEFINIR PERMISOS
PERSONA_ESTADO VARCHAR(50) NOT NULL -- ALTA O BAJA DE USUARIO
--FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

INSERT INTO PERSONA VALUES (1,'Santiago','Teves','Dueño','ALTA');
INSERT INTO PERSONA VALUES (2,'Nicolas','Maciel','Dueño','ALTA');
INSERT INTO PERSONA VALUES (3,'Franco','Guzman','Dueño','ALTA');

CREATE TABLE USUARIO (
USUARIO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
USUARIO_USER VARCHAR(50) NOT NULL,
USUARIO_PASS VARCHAR(50) NOT NULL,
USUARIO_ADMIN VARCHAR(1) NOT NULL
);

INSERT INTO USUARIO VALUES ('santi','santi123','Y');
INSERT INTO USUARIO VALUES ('nico','nico123','Y');
INSERT INTO USUARIO VALUES ('fran','fran123','Y');

CREATE TABLE PROVEEDOR (
PROVEEDOR_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
PROVEEDOR_NOMBRE VARCHAR (50) NOT NULL, -- NOMBRE PROVEEDOR
PROVEEDOR_RUBRO VARCHAR (50), --CATEGORIA A LA QUE PERTENCE EL PROVEEDOR
PROVEEDOR_CUIT VARCHAR (50) NOT NULL,
PROVEEDOR_FECHA_ALTA DATE NOT NULL, --FECHA DE ALTA DEL PROVEEDOR
PROVEEDOR_FECHA_BAJA DATE -- FECHA DE BAJA DEL PROVEEDOR
);

INSERT INTO PROVEEDOR VALUES ('N/A', 'N/A', 'N/A', GETDATE(), NULL);

CREATE TABLE MOVIMIENTO (
MOVIMIENTO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
PERSONA_ID INT NOT NULL,
PROVEEDOR_ID INT,
MOVIMIENTO_TIPO VARCHAR(20), --DEBE O HABER
IMPORTE DECIMAL (15,2) NOT NULL, --VALOR DE INGRESO O GASTO
MOVIMIENTO_FECHA_CREACION DATETIME NOT NULL, --FECHA DEL MOVIMIENTO
MOVIMIENTO_FECHA_ACT DATETIME, --FECHA DE ACTUALIZACION DEL MOVIMIENTO SI LO MODIFICAN VA JUNTO A COMENTARIO
MOVIMIENTO_COMENTARIO VARCHAR(50), --NOMBRE DEL PROVEEDOR O COMENTARIO PERSONALIZADO AL MOMENTO DE GENERAR EL MOVIMIENTO
FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID)
);

/*CREATE TABLE CAJA (
CAJA_ID INT NOT NULL PRIMARY KEY,
CAJA_TOTAL DECIMAL (18,2) NOT NULL,
CONSTRAINT CK_CAJA_Locked CHECK (CAJA_ID=1)
);

INSERT INTO CAJA VALUES (1,0);*/


 