--DROP DATABASE KIOSKO;
CREATE DATABASE KIOSKO;

USE [KIOSKO];

--DROP TABLE [dbo].[PERSONA];
--DELETE FROM [dbo].[PERSONA];

CREATE TABLE PERSONA (
PERSONA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
PERSONA_NOMBRE VARCHAR(50) NOT NULL, --NOMBRE DE LA PERSONA
PERSONA_APELLIDO VARCHAR (50) NOT NULL, --APELLIDO DE LA PERSONA
PERSONA_TIPO VARCHAR(50) NOT NULL, -- EMPLEADO O DUEÑO PARA DEFINIR PERMISOS
PERSONA_ESTADO VARCHAR(50) NOT NULL -- ALTA O BAJA DE USUARIO
)

--DROP TABLE [dbo].[PROVEEDOR];
--DELETE FROM [dbo].[PROVEEDOR];

CREATE TABLE PROVEEDOR (
PROVEEDOR_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
PROVEEDOR_NOMBRE VARCHAR (50) NOT NULL, -- NOMBRE PROVEEDOR
PROVEEDOR_RUBRO VARCHAR (50), --CATEGORIA A LA QUE PERTENCE EL PROVEEDOR
PROVEEDOR_FECHA_ALTA DATE NOT NULL, --FECHA DE ALTA DEL PROVEEDOR
PROVEEDOR_FECHA_BAJA DATE -- FECHA DE BAJA DEL PROVEEDOR
)


--DROP TABLE [dbo].[MOVIMIENTO];
--DELETE FROM [dbo].[MOVIMIENTO];

CREATE TABLE MOVIMIENTO (
MOVIMIENTO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
PERSONA_ID INT NOT NULL,
PROVEEDOR_ID INT,
MOVIMIENTO_TIPO VARCHAR(20), --DEBE O HABER
IMPORTE DECIMAL (15,2) NOT NULL, --VALOR DE INGRESO O GASTO

MOVIMIENTO_FECHA_CREACION DATE NOT NULL, --FECHA DEL MOVIMIENTO
MOVIMIENTO_FECHA_ACT DATE, --FECHA DE ACTUALIZACION DEL MOVIMIENTO SI LO MODIFICAN VA JUNTO A COMENTARIO
MOVIMIENTO_COMENTARIO VARCHAR(50), --NOMBRE DEL PROVEEDOR O COMENTARIO PERSONALIZADO AL MOMENTO DE GENERAR EL MOVIMIENTO
FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID) ,
--FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID)
);

CREATE TABLE CAJA (
CAJA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
MOVIMIENTO_ID INT NOT NULL,
CAJA_TOTAL DECIMAL (15,2) NOT NULL,
FOREIGN KEY (MOVIMIENTO_ID) REFERENCES MOVIMIENTO(MOVIMIENTO_ID)
);

CREATE TABLE LOGIN (
LOGIN_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
LOGIN_USER VARCHAR(50) NOT NULL,
LOGIN_PASS VARCHAR(50) NOT NULL,
);
 